### ISSUE TITLE
Request Image or Media size

### ISSUE THREAD

**Issue by ghost** [aledeg/FreshRSS-extensions#1]
Hello, 

First of all, thanks for this great extension.
Then I would like to ask a way to configure the max size (heigth/width) for the image to be displayed in order to not having too large image breaking the layout.

thanks.
p.

**Comment by aledeg** [comment]
Hi @prysme01,
sorry for the long delay. I found out about your issue only today. I might be a bit late now.

I am not sure if such option is useful in that context. You can manage that directly with Custom CSS extension. That's what I do.
I am using the following rule to achieve that.
```css
.reddit-image {max-height:70vh;}
```

Does this work for you?

**Comment by ghost** [comment]
yes thanks.

**Comment by aledeg** [comment]
@prysme01 if you update the extension, you might want to change the css since there was quite some changes. The css class ```reddit-image``` exists on 3 differents tags. You have it obviously on ```img``` and ```video``` tags. But there is also a ```div``` surrounding those tags if you want to style them differently.

The one I am using now is the following:
```css
img.reddit-image, video.reddit-image {max-height:80vh;}
```
With the newest version, if you use the style I told you about a year ago, you'll have something weird I guess.

Anyway, thank you for using that extension. I though I will be the only one using it :)

**Comment by ghost** [comment]
I will test that tomorrow. and I'm using it every days since, it's great ! thanks for your code !

**Comment by aledeg** [comment]
@prysme01 I've added the image height configuration. You may want to try it out!
